### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by DMGlion** [StartBootstrap/startbootstrap-clean-blog#1]
Hi, For my web page I am using only the contact form, But I am having an issue with it's implementation I got constantly the message. Sorry it seems that my mail server is not responding. Please try again later!
Any recommendation to make it work in hosting live. Thanks in advance.

**Comment by confusedsouls** [comment]
I think we cannot use github pages to host a mail service. Am I right?

**Comment by fiznool** [comment]
@confusedsouls you could use something like http://flipmail.co/

**Comment by humboldtux** [comment]
@confusedsouls @fiznool  I use http://formspree.io/ in my port of this theme to the Hugo static stie generator: https://github.com/humboldtux/sbcb-demo
