### ISSUE TITLE
NPM cannot find module

### ISSUE THREAD

**Issue by antamdesigns** [StartBootstrap/startbootstrap-clean-blog#101]
This was working yesterday but when I ran NPM start today I got this error.  I am new to using NPM.  Error: Cant find module  C:\inetpub\wwwroot\Sites\blog\startbootstrap-clean-blog-gh-pages\index.js

**Comment by davidtmiller** [comment]
Not sure on this, perhaps try reinstalling the package by running `npm i startbootstrap-clean-blog` and see if that helps!
