### ISSUE TITLE
Rendering content other than posts

### ISSUE THREAD

**Issue by erodriguez742** [StartBootstrap/startbootstrap-clean-blog#104]
I'm trying to insert an interactive map in the body of the bootstrap theme around line 73. I noticed the map only renders if I remove the line < div class="col-lg-8 col-md-10 mx-auto" >, but when that happens, the map renders over the page. If I keep the line in, the map is not visible.

**Comment by davidtmiller** [comment]
Not sure on this. It looks like the map doesn't work well within a Bootstrap column. It could have something to do with the position or display property of the map if I had to guess.
