### ISSUE TITLE
Add support for syntax highlighting

### ISSUE THREAD

**Issue by tmaier** [StartBootstrap/startbootstrap-clean-blog#128]
The jekyll version used to have support for syntax highlighting.
https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll/pull/8

It is gone.

Can you please add back the syntax.css file and include it?

Thanks!

**Comment by davidtmiller** [comment]
This is a bit outside of the scope of the theme moving forward. It's definitely something that can be added by the end user, but not something we are going to keep as part of the theme at the moment.
