### ISSUE TITLE
Show header on rollup does not work with Opera

### ISSUE THREAD

**Issue by donchambers** [StartBootstrap/startbootstrap-clean-blog#22]
Opera Test platform:

Version: 12.18 
Build: 1872 
Platform: Win32 
System: Windows 7

**Comment by davidtmiller** [comment]
I'll have to look into this, I've not tested this theme in Opera...

**Comment by eriknstr** [comment]
I have the same problem using Firefox 48.0 on Fedora 23 Linux.

**Comment by PirtleShell** [comment]
Are you both sure that `<script>` tag is properly included? I got a [Hexo](https://github.com/hexojs/hexo) version of this theme and it was missing the [theme's script](https://github.com/BlackrockDigital/startbootstrap-clean-blog/blob/master/js/clean-blog.js). After adding it in, my once only-on-the-top navbar was there as I scrolled up.
If you take a look at the source of the [example](https://blackrockdigital.github.io/startbootstrap-clean-blog/), you'll see the last script tag is
```html
<script src="js/clean-blog.min.js"></script>
```

**Comment by eriknstr** [comment]
Testing https://blackrockdigital.github.io/startbootstrap-clean-blog/ using FreeBSD 11.0 with a cleanly installed Firefox 49.0 and no extensions, it works. You might be right, @PirtleShell. When I tested using Firefox 48.0 on Fedora 23 Linux, I did not check to ensure that scripts were loaded. Will test again when I'm back at my desktop computer.

**Comment by eriknstr** [comment]
Worked fine in Firefox 49.0 on Fedora 23 Linux when I tested now. Don't know what is different now from the last time I tested, aside from that I have updated Firefox from 48 to 49 in the meantime.

**Comment by davidtmiller** [comment]
Still keeping an eye on this. With #49 I need to do some cross-browser testing to see what's going on here.

**Comment by curtismcginity** [comment]
I'm running into the same issue (Safari 9.1.2). Any suggestions for working on a fix?

**Comment by davidtmiller** [comment]
I guess I don't like the idea of forcing the `.container-fluid` for formatting reasons. I will keep this open for now and see if the upcoming Bootstrap 4.5 changes, and eventually Bootstrap 5, addresses this issue.
