### ISSUE TITLE
Media query for masthead

### ISSUE THREAD

**Issue by pgrandinetti** [StartBootstrap/startbootstrap-clean-blog#83]
I would like to serve different images as background in the `<header class="masthead">` element. The actual image would be chosen with media query on the device's size (basically, always the same figure but with different file size).
I was wondering if it's something you've already done, or if you have suggestions/templates.
Cheers

**Comment by davidtmiller** [comment]
That is something that should be easy enough to accomplish with a little bit of custom CSS. Just use media queries in a CSS file targeting the masthead and use different background images in each media query.
