### ISSUE TITLE
Contact form using formspree is broken

### ISSUE THREAD

**Issue by schantepie** [StartBootstrap/startbootstrap-clean-blog#89]
Dear developpers, 

I am using the template designed for Github.
The contact form implemented in this template use formspree.io to redirect emails as github only accept static pages (not php).K

Nevertheless, I have the message "Sorry XXX, it seems that my mail server is not responding. Please try again later". 
The fact is I do not received the email from formspree.io to validate my account. I try several e-mail accounts, I do not received this email.

Do you have ideas to fix this?

best

**Comment by davidtmiller** [comment]
I'm not sure on this one, I would look at to the formspree docs to see if you can resolve this one. I also have a formspree working example over at https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll which might be able to help
